language: ruby

rvm:
  - 2.5.5
  - 2.6.3
  - 2.7.1

gemfile:
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
  - gemfiles/rails_61.gemfile

sudo: false

script: 'bundle exec rake'
